### ISSUE TITLE
Broadcast Hub doesn't handle cache-line puts correctly

### ISSUE THREAD

**Issue by aswaterman** [ucb-bar/uncore#27]
It only passes through the first beat of data correctly.  The others don't make it into the sdq.

This is easily verified by not running with +loadmem, e.g., on my machine:

    ./simv-Top-DefaultVLSIConfig /scratch/waterman/toolchain/riscv64-unknown-elf/share/riscv-tests/isa/rv64ui-p-add

@palmer-dabbelt Should we change the regression scripts to not use +loadmem?

**Comment by donggyukim** [comment]
Yes, I just found it, too. Interestingly, it works both on rocket and boom with l2 caches.

**Comment by aswaterman** [comment]
thanks!
