### ISSUE TITLE
Bug w/ Partial Writemasks in L2 Cache

### ISSUE THREAD

**Issue by zhemao** [ucb-bar/uncore#31]
I'm running into an issue with the L2 cache not reading the old data when handling a put or put-block with partial writemasks. The origin of the bug appears to be in the following function.

    def addPendingBitWhenBeatHasPartialWritemask(in: DecoupledIO[AcquireFromSrc]): UInt = {
      val a = in.bits                                                                     
      val isPartial = a.wmask() =/= Acquire.fullWriteMask                                 
      addPendingBitWhenBeat(in.fire() && isPartial && Bool(ignoresWriteMask), a)          
    }

Shouldn't that boolean expression on the last line be `in.fire() && (isPartial || Bool(ignoresWriteMask)`. I assume the intended behavior is that the pending bit will always be added when "ignoresWriteMask" is true. The way it is currently, if ignoresWriteMask is false, the pending bit will never be added.

**Comment by hcook** [comment]
Closed by 9978139f4f6276db01b2a46b3438ef0fe73d9d59
