### ISSUE TITLE
TileLink address mismatch when using TileLink for non-cache line size

### ISSUE THREAD

**Issue by wsong83** [ucb-bar/uncore#36]
The current definition of TileLink addresses are:
  val tlBeatAddrBits = log2Up(tlDataBeats)
  val tlByteAddrBits = log2Up(tlWriteMaskBits)
  val tlBlockAddrBits = p(PAddrBits) - p(CacheBlockOffsetBits)

This implies the size of a TileLink transaction is always assumed to be a cache line.
If I use TileLink for a transactions of 64-bits (bits per beat 32, beats 2)
Then the Acquire.full_addr() will get it wrong as CacheBlockOffsetBits != 64*8

  def full_addr(dummy: Int = 0) = Cat(this.addr_block, this.addr_beat, this.addr_byte())

Also if I define beats == 1,
Acquire.full_addr() does not work properly (beat field should be empty).

I am trying to use a 64-bit single beat TileLink for some IO devices.

So the only way I can get around this perhaps is to use overrideDataBitsPerBeat Option and always set dataBits to 64*8?

**Comment by zhemao** [comment]
So, currently it is not possible to perform a 64-bit transaction over a 32-bit wide bus in TileLink. We are in the process of rethinking the protocol so that the logical data width can be decoupled from the physical data width.
