### ISSUE TITLE
id field in HtifIO

### ISSUE THREAD

**Issue by jia1546** [ucb-bar/uncore#46]
Initially, the id field in HtifIO is used to generate core-id for tiles, which is now from PRCI. So, I suggest that the id filed in HtifIO should be removed. @zhemao

**Comment by zhemao** [comment]
Can't we get rid of HtifIO completely now? We no longer connect the SCRs and id and reset are taken care of by PRCI.

**Comment by zhemao** [comment]
Okay, it looks like we still use reset, but that's it.

**Comment by zhemao** [comment]
I think the plan is to eventually get rid of HTIF completely, so I don't think it's worthwhile to change anything right now.
